add container-network-attach-failed event

diff --git a/test/fixtures/weaveMock b/test/fixtures/weaveMock
--- a/test/fixtures/weaveMock
+++ b/test/fixtures/weaveMock
@@ -4,17 +4,17 @@
 # ./weaveMock <WEAVE_COMMAND> [...args...]
 #
 WEAVE_COMMAND=$1
+echo $* > ./weaveMockArgs
+
 case "$WEAVE_COMMAND" in
   launch-router)
-    echo $* > ./weaveMockArgsLaunch
     echo 237c9ccf14e89a6e23fb15f2d9132efd98878f6267b9f128f603be3b3e362472
     ;;
   attach)
     echo 10.0.17.38
-    echo $* > ./weaveMockArgsAttach
     ;;
-  *)
-    echo "Unknown weave command '$WEAVE_COMMAND'" >&2
+  fail)
+    echo "weave command $* failed" >&2
     exit 1
     ;;
 esac
